CREATE TABLE IF NOT EXISTS comments (
id INTEGER PRIMARY KEY ON CONFLICT ROLLBACK AUTOINCREMENT NOT NULL ON CONFLICT ROLLBACK UNIQUE ON CONFLICT ROLLBACK,
region_id INTEGER REFERENCES regions (id) NOT NULL ON CONFLICT ROLLBACK,
towns_id INTEGER REFERENCES towns (id) NOT NULL ON CONFLICT ROLLBACK,
user_name STRING (64) NOT NULL ON CONFLICT ROLLBACK,
user_patronim STRING (64),
user_last_name STRING (64) NOT NULL ON CONFLICT ROLLBACK,
user_email STRING (128),
user_phone STRING (10),
comment TEXT (2048) NOT NULL ON CONFLICT ROLLBACK,
pub_datetime DATETIME NOT NULL ON CONFLICT ROLLBACK DEFAULT (datetime('now', 'localtime'))
);

CREATE TABLE IF NOT EXISTS towns (
id INTEGER PRIMARY KEY ON CONFLICT ROLLBACK AUTOINCREMENT UNIQUE ON CONFLICT ROLLBACK NOT NULL ON CONFLICT ROLLBACK,
region_id INTEGER REFERENCES regions (id) ON DELETE CASCADE NOT NULL ON CONFLICT ROLLBACK,
name STRING (128) UNIQUE ON CONFLICT ROLLBACK NOT NULL ON CONFLICT ROLLBACK
);

CREATE TABLE IF NOT EXISTS regions (
id INTEGER PRIMARY KEY ON CONFLICT ROLLBACK AUTOINCREMENT NOT NULL ON CONFLICT ROLLBACK UNIQUE ON CONFLICT ROLLBACK,
name STRING (128) UNIQUE ON CONFLICT ROLLBACK NOT NULL ON CONFLICT ROLLBACK
);